### ISSUE TITLE
check 59, parser errors

### ISSUE THREAD

**Issue by larshp** [larshp/abapOpenChecks#413]
2 parser errors,

```abap
IF NOT line_exists( lt_bar[ name = 'BLAH' ] ) AND iv_foo IS NOT INITIAL.

IF lv_blah IS INSTANCE OF if_sxml_value_node.
```

**Comment by redhawk07** [comment]
We also get parser errors if a method is called in an IF or a CHECK statement like in this example:
`CHECK lv_value IS INITIAL OR
lr_object->get_type( ) = lv_value.`

**Comment by larshp** [comment]
Hi,
Thanks for reporting, but I did not succeed in reproducing the error, are you running the latest version?

test report:
```abap
REPORT ztest001.

START-OF-SELECTION.
  PERFORM run.

CLASS lcl_class DEFINITION.
  PUBLIC SECTION.
    METHODS: get_type
      RETURNING VALUE(rv_foo) TYPE xubname.
ENDCLASS.

CLASS lcl_class IMPLEMENTATION.
  METHOD get_type.

  ENDMETHOD.
ENDCLASS.

FORM run.

  DATA: lv_value  TYPE c LENGTH 1,
        lr_object TYPE REF TO lcl_class.

  CREATE OBJECT lr_object.

  CHECK lv_value IS INITIAL OR lr_object->get_type( ) = lv_value.

ENDFORM.
```

**Comment by larshp** [comment]
as a workaround it is possible to ignore the parser errors in the check configuration

**Comment by redhawk07** [comment]
Thanks for the quick reply. I installed the version that was available on 21.02.2018 (one week ago). There are a few things to mention:
- The CHECK statement is split into two lines (the OR is at the end of the first line).
- The code is not in a local class, but in a global one and also in a nested IF at level 3.
- I shortened the example by the interface. Originally the call is lr_object->intf~get_type( ).
- Your sample report doesn't bring up the error.
- Due to the parser error, in ZCL_AOC_BOOLEAN_NODE a NULL referenced node is added to mt_children. This leads to a dump in the WALK method afterwards.

If you have other questions, please let me know.

**Comment by larshp** [comment]
okay, can you help reproducing the error in a report with local classes/interfaces? I think it should be possible, check 59 just looks at the statement, not the overall structure of the program

**Comment by redhawk07** [comment]
Ok.
I now implemented a report that's as short as possible. It doesn't make any sense other than showing the problem. If you run check 59 against it, it dumps:

```
REPORT ZTEST_CHECK59_DUMP.

CLASS lcl_test DEFINITION
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    CLASS-METHODS do_it .

ENDCLASS.

CLASS lcl_test IMPLEMENTATION.

  METHOD do_it.

    DATA:
      ls_message TYPE bapiret2,
      lr_object  TYPE REF TO /ui2/cl_edm_model_entity.

    IF ls_message-type EQ 'E'   OR
       ( ls_message-type EQ 'A' AND
         lr_object->/ui2/if_edm_model_entity~get_entity_name( ) = SPACE ).

    ENDIF.
  ENDMETHOD.

ENDCLASS.

START-OF-SELECTION.
  lcl_test=>do_it( ).
```

**Comment by larshp** [comment]
Thanks, I also get a dump with above code

I'm currently quite busy with real work stuff, but might get some time to look into it in the weekend

**Comment by larshp** [comment]
@redhawk07 try again, latest version, the namespace `/ui2/` was causing some issues

**Comment by redhawk07** [comment]
It works now :-) Thanks for your quick change.

**Comment by larshp** [comment]
cool, closing
